# Generated by Django 4.2.6 on 2023-11-06 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_products', models.CharField(max_length=30, verbose_name='Название')),
                ('price_products', models.IntegerField(verbose_name='Цена')),
                ('description_products', models.TextField(max_length=250, verbose_name='Описание')),
                ('description_products_min', models.CharField(max_length=50, verbose_name='Описание краткое')),
                ('numb_photo', models.TextField(max_length=20, verbose_name='Нумерация фото')),
            ],
        ),
    ]
