# Generated by Django 4.2.6 on 2023-11-12 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_products_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBasket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(default=None, max_length=128, verbose_name='Ключ сессии')),
                ('name_products', models.CharField(default=None, max_length=30, verbose_name='Название')),
                ('price_products', models.IntegerField(default=None, verbose_name='Цена')),
                ('count_products', models.TextField(default=None, max_length=250, verbose_name='Количество')),
                ('description_products', models.CharField(default=None, max_length=50, verbose_name='Краткое описание ')),
                ('numb_photo', models.TextField(default=None, max_length=20, verbose_name='Нумерация фото')),
            ],
            options={
                'verbose_name': 'Товар в корзине',
                'verbose_name_plural': 'Товары в корзине',
            },
        ),
    ]
