# Generated by Django 4.2.6 on 2023-11-12 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_productbasket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbasket',
            name='count_products',
            field=models.IntegerField(default=None, max_length=250, verbose_name='Количество'),
        ),
    ]
