# Generated by Django 4.2.6 on 2023-11-01 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artiles',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterField(
            model_name='artiles',
            name='full_text',
            field=models.TextField(verbose_name='Сатья'),
        ),
    ]
