# Generated by Django 4.2.6 on 2023-11-11 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_articles_options_alter_articles_full_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artiles',
            name='title',
            field=models.CharField(max_length=25, verbose_name='Название: '),
        ),
    ]
